version: '3'

volumes:
  notify-mysql-data:
    driver: local

services:
  php:
    container_name: notify-php
    tty: true
    build:
      context: ./
    volumes:
      - ./:/var/www
    ports:
      - "9550:9501"
    entrypoint: bash -c "composer install && php bin/hyperf.php server:watch"
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_NAME}
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: notify-mysql
    ports:
      - "3350:3316"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notify
      MYSQL_TCP_PORT: 3316
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: notify-rabbitmq
    ports:
      - "5650:5672"
      - "15650:15672"
  redis:
    image: redis:latest
    container_name: notify-redis
    restart: unless-stopped
    ports:
      - "6550:6379"
    expose:
      - "6379"
