version: '3'
services:
  hyperf-php:
    container_name: hyperf-php
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/var/www
    ports:
      - 9550:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: hyperf-mysql
    volumes:
      - ./hyperf-mysql-data:/var/lib/mysql
    ports:
      - 3350:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperf_database
      MYSQL_TCP_PORT: 3306
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: hyperf-rabbitmq
    ports:
      - 5650:5672
      - 15650:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  redis:
    image: redis:latest
    container_name: hyperf-redis
    restart: unless-stopped
    ports:
      - 6550:6379
    expose:
      - "6379"
    volumes:
      - ./hyperf-redis-data:/data
networks:
  hyperf-php-network:
    driver: bridge
